server:
  port: 10050
spring:
  application:
    name: reggie_take_out
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: znx123
      mysql: usePingMethod=false
  redis:
    host: 192.168.111.132
    port: 6379
    database: 1
    timeout: 10000
  cache:
    redis:
      time-to-live: 1800000 #设置缓存数据的过期时间
mybatis-plus:
  configuration:
    #???????????????????????????????????????
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # ??????
      id-type: ASSIGN_ID

#cache:
#  redis:
#    time-to-live: 1800000 #设置缓存数据的过期时间
reggie:
  path: D:\
